### ISSUE TITLE
How to build NSG index for 1B dataset?

### ISSUE THREAD

**Issue by gloriallluo** [johnpzh/iQAN_AE#2]
Dear author,

Hi, I am currently trying to build an NSG index for deep1B on a machine with 1.4TB of DRAM. However, I am facing some difficulties where either the required memory exceeds what I can provide or the time required for building the index is unacceptable. I noticed that in your paper, you were able to build an NSG for the deep1B dataset in less than 10 days. Could you please tell me which libraries you used and how you chose the parameters?

Thank you very much!

**Comment by johnpzh** [comment]
Hi @gloriallluo . I totally understand that building an NSG index for Deep1B is not easy. After several years, I might have forgotten some details, but I can try my best to help you.

First, I had used just [the EFANNA_graph](https://github.com/ZJULearning/efanna_graph) and [the NSG](https://github.com/ZJULearning/nsg) to build the index, as recommended by the authors. However, I think there are some issues in the `efanna_graph` code for very large datasets.
1. The size for [this `new` statement](https://github.com/ZJULearning/efanna_graph/blob/50c4445a9e654f845213f9454106bc038a278764/tests/test_nndescent.cpp#L19) is not correct and too large. You may correct it with a right number. 
2. At the same [line](https://github.com/ZJULearning/efanna_graph/blob/50c4445a9e654f845213f9454106bc038a278764/tests/test_nndescent.cpp#L19), the type of `num` and `dim` is `unsigned`, which might cause overflow. Thus, you may use `uint64_t` for them. Btw, this issue is spotted by Yifu Deng@Michigan Techonological University.
3. [This parallel for-loop](https://github.com/ZJULearning/efanna_graph/blob/50c4445a9e654f845213f9454106bc038a278764/src/index_graph.cpp#L141) requires very large memory footprint, especially when `num_threads` and `N` are large. You may consider limiting the number of threads used there.

Second, I think I had tried some particular sets of parameters when building the index. For the kNN graph, I might have used
| Dataset | K  | L  | iter | S  | R  |
|---------|----|----|------|----|----|
| Deep1B  | 10 | 10 | 10   | 10 | 10 |

For the NSG index, I might have used
| Dataset | L | R  | C  |
|---------|---|----|----|
| Deep1B  | 2 | 70 | 70 |

I just found these numbers from some old notes, so I cannot guarantee their correctness. My bad if they would not work.

That's all I can think of for now. Hope this is helpful.

**Comment by gloriallluo** [comment]
Thank you very much for your detailed reply!!
